### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HadrienG** [HadrienG/2019_classifiers_benchmark#1]
This issue will track progress on the project evolution. See it as a to-do list for the project

- [x] Make a roadmap

## Software tested

- [ ] Agree on a preliminary list of software to test (#2 )

## Databases

- [x] How many genomes? (#3 )
- [x] Which genomes to select? (#3 )
- [x] Download genomes
- [ ] Build databases for the selected software

## Datasets

- [x] Agree on the number of datasets to simulate (#4 )
- [x] Agree on the abundance levels (#4 )
- [x] Simulate dataets

## Benchmarking

- [ ] Lay down rules to be able to add software to the test list if needed
- [ ] Run the selected software on all the datasets
- [ ] Convert output in a common format

## Analysis

- [ ] Which software on average is more sensitive
- [ ] Species / genus / ... levels
- [ ] False positives?
- [ ] Differences in identifying bacteria / viruses / archaea
- [ ] Speed / Memory consumption
- [ ] Conclusions and eventual recommendations
